version: "3"

services:
    redis:
        image: redis:6.2.6
        container_name: cache
        expose:
            - 6379
        command: ["redis-server", "--bind", "redis", "--port", "6379", "--maxmemory ${maxmemory}","--maxmemory-policy ${maxmemorypolicy}"]
    database:
        image: docker.io/bitnami/postgresql:11
        container_name: pg-db
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - pg-db.env
        ports:
            - '5432:5432'
    server:
        build: 
            context: ./
            dockerfile: ./server/Dockerfile
        container_name: py-server
        volumes:
            - ./server:/home/app
        ports:
            - "8000:8000"
        depends_on:
            - database
            - redis
    client:
        build: 
            context: ./
            dockerfile: ./client/Dockerfile
        container_name: node-client
        environment:
            - REDIS_URL=redis://cache
        volumes:
            - ./client:/home/client
        ports:
            - "3000:3000"
        depends_on:
            - redis
            - server
